version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - govet

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks:
      - "all"
      - "-ST1000"
      - "-SA*"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0