vars:
  PUID:
    value: "1000"
    required: false
  PGID:
    value: "1000"
    required: false
  TZ:
    value: "UTC"
    required: false
  SUPERUSER_EMAIL:
    value: ""
    required: false

secrets:
  SECRET_KEY:
    required: true
  SUPERUSER_PASSWORD:
    required: true

databases:
  postgres:
    database: netbox
    user: netbox
    env:
      host: NB_DB_HOST
      port: NB_DB_PORT
      user: NB_DB_USER
      password: NB_DB_PASS
      database: NB_DB_NAME
ports:
  web:
    port: 8080
