vars:
  ADMIN_USERNAME:
    value: "admin"
    required: false

secrets:
  ADMIN_PASSWORD:
    required: true

databases:
  - postgres:
      database: miniflux
      user: miniflux
      dsn_template: "postgres://{user}:{password}@{host}:{port}/{database}?sslmode=disable"
      env:
        dsn: DATABASE_URL
ports:
  - 8080