vars:
  PUID:
    value: "1000"
    required: false
  PGID:
    value: "1000"
    required: false

secrets: {}

databases:
  - postgres:
      database: forgejo
      user: forgejo
      env:
        host: F_DB_HOST
        port: F_DB_PORT
        user: F_DB_USER
        password: F_DB_PASS
        database: F_DB_NAME
ports:
  - 3000
  - ssh:22
