vars:
  PUID:
    value: "1000"
    required: false
  PGID:
    value: "1000"
    required: false
  TZ:
    value: "UTC"
    required: false
  MEDIA_PATH:
    value: "/mnt/media"
    required: false
  DOWNLOADS_PATH:
    value: "/mnt/downloads"
    required: false

secrets: {}
ports:
  web:
    port: 7878
