// Package caddy validates and reloads the running Caddy container, and
// regenerates a service's Caddy config from its declaration.
//
// Every route is a file generated by internal/configgen from the service's
// config.yaml `ports:` declaration or its caddy.routes.conf. Nothing here
// writes routes for a new layer — that is `homelab enable` — it only refreshes
// what is already on and makes sure a bad config never outlives a reload.
package caddy

import (
	"fmt"
	"os"

	"github.com/groot/homelab/internal/configgen"
	"github.com/groot/homelab/internal/network"
	"github.com/groot/homelab/internal/network/layers"
	"github.com/groot/homelab/internal/routing"
	"github.com/groot/homelab/internal/run"
)

const (
	caddyContainer = "caddy"
	caddyFile      = "/etc/caddy/Caddyfile"
	caddyAdapter   = "caddyfile"
)

// Manager performs caddy routing operations for a given repo root.
type Manager struct {
	RepoRoot string
	runner   *run.Commander
	// reloadFn, if non-nil, replaces the default Reload() implementation.
	// Inject a no-op in tests to avoid requiring a live Docker/Caddy instance.
	reloadFn func() error
}

// New returns a Manager that streams docker output to the terminal.
func New(repoRoot string) *Manager {
	return &Manager{RepoRoot: repoRoot, runner: run.Default()}
}

// NewWithRunner returns a Manager using a custom Commander.
// Pass a Commander backed by a bytes.Buffer when output must be captured
// (e.g. while an animated spinner is active).
func NewWithRunner(repoRoot string, r *run.Commander) *Manager {
	return &Manager{RepoRoot: repoRoot, runner: r}
}

// newForTest returns a Manager whose Reload() is replaced by fn.
// Only used in tests within this package.
func newForTest(repoRoot string, reloadFn func() error) *Manager {
	return &Manager{RepoRoot: repoRoot, runner: run.Default(), reloadFn: reloadFn}
}

// ── Per-service config reload ─────────────────────────────────────────────────

// ReloadService regenerates a service's Caddy config for every layer it is
// currently on and reloads Caddy once — picking up edits to its config.yaml
// ports or caddy.routes.conf. A layer that is off stays off, the --name it was
// enabled with is kept (it is read back from the generated block), and so is a
// --ports selection (only the ports that already have a block are rewritten).
//
// Only Host-routed layers are refreshed: a tor or ygg address (an onion, an
// allocated mesh port) belongs to the layer's daemon, which this does not ask.
func (m *Manager) ReloadService(name string) error {
	info, err := configgen.LoadServiceInfo(m.RepoRoot, name)
	if err != nil {
		return err
	}
	snap, err := m.Snapshot()
	if err != nil {
		return err
	}

	reloaded := false
	for _, l := range layers.New(m.RepoRoot, nil, nil).All() {
		if _, ok := l.(network.HostRouted); !ok {
			continue
		}
		portNames, active := activePorts(m.RepoRoot, l.ConfDir(), info)
		if !active {
			continue
		}
		e, err := configgen.Resolve(m.RepoRoot, name, configgen.GeneratedHost(m.RepoRoot, l, name), portNames)
		if err == nil {
			err = routing.Refresh(m.RepoRoot, l, e)
		}
		if err != nil {
			return fmt.Errorf("%s: %w", l.Name(), err)
		}
		reloaded = true
	}
	if !reloaded {
		return fmt.Errorf("service %q has no active routes to reload", name)
	}
	return m.ReloadOrRestore(snap)
}

// activePorts reports whether a layer has any generated block for the service
// and, for a port-driven service, which declared ports have one. A
// routes-driven service has a single block per layer and no port selection.
func activePorts(root, confDir string, info configgen.ServiceInfo) ([]string, bool) {
	if info.Routes != "" || len(info.Ports) == 0 {
		return nil, exists(configgen.GeneratedFilePath(root, confDir, info.Name, ""))
	}
	ports, err := configgen.ResolvePorts(info.Ports, nil)
	if err != nil {
		return nil, false
	}
	var names []string
	for _, p := range ports {
		if exists(configgen.GeneratedFilePath(root, confDir, info.Name, p.Name)) {
			names = append(names, p.Name)
		}
	}
	return names, len(names) > 0
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// ── Caddy lifecycle ───────────────────────────────────────────────────────────

// Validate runs `caddy validate` inside the caddy container.
func (m *Manager) Validate() error {
	return m.runner.DockerExec(caddyContainer,
		"caddy", "validate",
		"--config", caddyFile,
		"--adapter", caddyAdapter,
	)
}

// Reload validates then gracefully reloads Caddy (zero downtime, no cert re-issuance).
// If reloadFn is set (e.g. in tests), it is called instead.
func (m *Manager) Reload() error {
	if m.reloadFn != nil {
		return m.reloadFn()
	}
	if err := m.Validate(); err != nil {
		// A stopped Caddy fails validation too; that is not a config problem
		// and must not trigger a rollback in ReloadOrRestore.
		if m.runner.ContainerStatus(caddyContainer) != "running" {
			return fmt.Errorf("caddy validate failed (is the caddy container running?): %w", err)
		}
		return fmt.Errorf("%w: %w", ErrInvalidConfig, err)
	}
	// Use --force to ensure the admin API fully replaces the active config
	// rather than skipping if the new config is structurally identical.
	return m.runner.DockerExec(caddyContainer,
		"caddy", "reload",
		"--config", caddyFile,
		"--adapter", caddyAdapter,
		"--force",
	)
}
