vault.{$PUB_SUBDOMAIN}.{$DOMAIN} {
    import wildcard_tls

    reverse_proxy vaultwarden:80
    reverse_proxy /notifications/hub vaultwarden:3012
    reverse_proxy /notifications/hub/negotiate vaultwarden:80
}
