package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/groot/homelab/internal/run"
	"github.com/groot/homelab/internal/tui/styles"
	"github.com/spf13/cobra"
)

const torContainer = "tor"
const torHiddenServiceDir = "/var/lib/tor/hidden_service"

var torCmd = &cobra.Command{
	Use:   torContainer,
	Short: "Manage Tor onion service proxy",
	Long:  "Inspect gnzsnz/torproxy and manage .onion hidden services.",
}

// ── status ────────────────────────────────────────────────────────────────────

var torStatusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show Tor container and onion service status",
	RunE: func(cmd *cobra.Command, args []string) error {
		root := configDir()

		fmt.Printf("\n%s\n\n", styles.Header.Render("Tor Onion Service Proxy"))

		if !extEnabled(root, "tor") {
			fmt.Printf("  %s  Tor not enabled.\n", styles.Warning.Render("!"))
			fmt.Printf("  Run %s to enable.\n\n",
				styles.Primary.Render("homelab ext enable tor"))
			return nil
		}

		state := containerStatus(torContainer)
		if state == containerStateRunning {
			fmt.Printf("  %s  tor  %s\n", styles.Success.Render("✓"), styles.StateTag(state))
		} else {
			fmt.Printf("  %s  tor  %s\n", styles.Err.Render("✗"), styles.StateTag(state))
			fmt.Printf("\n  Start with: %s\n\n", styles.Primary.Render("homelab start"))
			return nil
		}

		// List active onion services
		torrcDir := filepath.Join(root, "tor", "torrc.d")
		entries, err := os.ReadDir(torrcDir)
		if err != nil {
			fmt.Printf("  %s  Could not read %s\n", styles.Warning.Render("!"), torrcDir)
			return nil
		}

		fmt.Printf("\n  %s\n", styles.Bold.Render("Active onion services"))
		found := false
		for _, e := range entries {
			if !strings.HasSuffix(e.Name(), ".conf") {
				continue
			}
			name := strings.TrimSuffix(e.Name(), ".conf")
			onion, err := exec.Command( // nosec G204 -- binary is "docker", paths are programmatic
				"docker", "exec", torContainer,
				"cat", filepath.Join(torHiddenServiceDir, name, "hostname"),
			).Output()
			if err != nil {
				continue
			}
			found = true
			fmt.Printf("  %s  %s → %s",
				styles.Muted.Render("↳"),
				styles.Bold.Render(name),
				styles.Primary.Render(strings.TrimSpace(string(onion))),
			)
			fmt.Println()
		}
		if !found {
			fmt.Printf("  %s  (none — run %s)\n",
				styles.Muted.Render("!"),
				styles.Primary.Render("homelab tor enable <service>"))
		}
		fmt.Println()
		return nil
	},
}

// ── logs ──────────────────────────────────────────────────────────────────────

var torLogsCmd = &cobra.Command{
	Use:   "logs",
	Short: "Stream tor container logs",
	RunE: func(cmd *cobra.Command, args []string) error {
		root := configDir()
		env := buildEnv(root, "")
		return run.Default().DockerComposeEnv(
			run.CoreComposeFile(root),
			env,
			withProfiles(root, "logs", "-f", torContainer)...,
		)
	},
}

// ── list ──────────────────────────────────────────────────────────────────────

var torListCmd = &cobra.Command{
	Use:   "list",
	Short: "List active onion services with .onion addresses",
	RunE: func(cmd *cobra.Command, args []string) error {
		root := configDir()
		torrcDir := filepath.Join(root, "tor", "torrc.d")
		entries, err := os.ReadDir(torrcDir)
		if err != nil {
			return fmt.Errorf("reading %s: %w", torrcDir, err)
		}

		fmt.Printf("\n%s\n\n", styles.Header.Render("Onion Services"))

		found := false
		for _, e := range entries {
			if !strings.HasSuffix(e.Name(), ".conf") {
				continue
			}
			name := strings.TrimSuffix(e.Name(), ".conf")
			onion, err := exec.Command( // nosec G204 -- binary is "docker", paths are programmatic
				"docker", "exec", torContainer,
				"cat", filepath.Join(torHiddenServiceDir, name, "hostname"),
			).Output()
			if err != nil {
				fmt.Printf("  %s  %s  %s\n",
					styles.Warning.Render("!"), styles.Bold.Render(name),
					styles.Muted.Render("(container not running or service not yet ready)"))
				continue
			}
			found = true
			fmt.Printf("  %s  %s → %s\n",
				styles.Dot(true, true),
				styles.Bold.Render(name),
				styles.Primary.Render(strings.TrimSpace(string(onion))),
			)
		}
		if !found {
			fmt.Printf("  %s  (none)\n", styles.Muted.Render("!"))
		}
		fmt.Println()
		return nil
	},
}

// ── enable ────────────────────────────────────────────────────────────────────

var torEnableCmd = &cobra.Command{
	Use:   "enable <service>",
	Short: "Expose a service as a .onion hidden service",
	Long: `Create a Tor hidden service for the given service.

The .onion address is auto-generated by Tor and persisted in the tor-data
Docker volume. If the volume is removed, the address changes.

After enabling, the .onion address can be found with:
  homelab tor list

Use --port to override the port detected from caddy.conf.`,
	Args:              cobra.ExactArgs(1),
	ValidArgsFunction: completeServiceNames,
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		root := configDir()

		port, _ := cmd.Flags().GetString("port")
		if port == "" {
			var err error
			port, err = detectServicePort(root, name)
			if err != nil {
				return fmt.Errorf("detecting port for %s: %w\n  Use --port to specify explicitly", name, err)
			}
		}

		// Write config snippet to torrc.d/<name>.conf
		confDir := filepath.Join(root, "tor", "torrc.d")
		if err := os.MkdirAll(confDir, 0o750); err != nil {
			return fmt.Errorf("creating torrc.d: %w", err)
		}
		confPath := filepath.Join(confDir, name+".conf")
		content := fmt.Sprintf("HiddenServiceDir %s/%s\nHiddenServicePort %s %s:%s\n",
			torHiddenServiceDir, name, port, name, port)

		if err := os.WriteFile(confPath, []byte(content), 0o600); err != nil {
			return fmt.Errorf("writing %s: %w", confPath, err)
		}
		fmt.Printf("  %s  %s written\n", styles.Success.Render("✓"), confPath)

		// Reload tor config
		if err := ReloadTor(); err != nil {
			return fmt.Errorf("reloading tor: %w", err)
		}
		fmt.Printf("  %s  Tor config reloaded\n", styles.Success.Render("✓"))

		// Show .onion address if available
		onion, _ := exec.Command(
			"docker", "exec", torContainer,
			"cat", filepath.Join(torHiddenServiceDir, name, "hostname"),
		).Output()
		if len(onion) > 0 {
			fmt.Printf("  %s  Onion address: %s\n",
				styles.Primary.Render("→"),
				styles.Bold.Render(strings.TrimSpace(string(onion))))
		} else {
			fmt.Printf("  %s  Onion address will appear after first connection — run %s\n",
				styles.Muted.Render("!"),
				styles.Primary.Render("homelab tor list"))
		}
		fmt.Println()
		return nil
	},
}

var torEnablePort string

func init() {
	torEnableCmd.Flags().StringVar(&torEnablePort, "port", "", "Override service port")
}

// ── disable ───────────────────────────────────────────────────────────────────

var torDisableCmd = &cobra.Command{
	Use:               "disable <service>",
	Short:             "Remove a .onion hidden service",
	Args:              cobra.ExactArgs(1),
	ValidArgsFunction: completeServiceNames,
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		root := configDir()
		confPath := filepath.Join(root, "tor", "torrc.d", name+".conf")

		if _, err := os.Stat(confPath); os.IsNotExist(err) {
			return fmt.Errorf("no onion service config found for %q", name)
		}
		if err := os.Remove(confPath); err != nil {
			return fmt.Errorf("removing %s: %w", confPath, err)
		}
		fmt.Printf("  %s  %s removed\n", styles.Warning.Render("→"), confPath)

		if err := ReloadTor(); err != nil {
			return fmt.Errorf("reloading tor: %w", err)
		}
		fmt.Printf("  %s  Tor config reloaded\n", styles.Success.Render("✓"))
		fmt.Println()
		return nil
	},
}

// ── helpers ───────────────────────────────────────────────────────────────────

// ReloadTor sends SIGHUP to the tor process inside the container.
func ReloadTor() error {
	return run.Default().DockerExec(torContainer,
		"sh", "-c", "kill -HUP $(pidof tor)")
}

// TorServicePath returns the torrc.d config path for a service.
func TorServicePath(root, name string) string {
	return filepath.Join(root, "tor", "torrc.d", name+".conf")
}

// AppendTorService writes a torrc.d config for a service.
func AppendTorService(root, name, port string) error {
	confDir := filepath.Join(root, "tor", "torrc.d")
	if err := os.MkdirAll(confDir, 0o750); err != nil {
		return fmt.Errorf("creating torrc.d: %w", err)
	}
	confPath := TorServicePath(root, name)
	content := fmt.Sprintf("HiddenServiceDir %s/%s\nHiddenServicePort %s %s:%s\n",
		torHiddenServiceDir, name, port, name, port)
	return os.WriteFile(confPath, []byte(content), 0o600)
}

// RemoveTorService removes a torrc.d config for a service.
func RemoveTorService(root, name string) error {
	confPath := TorServicePath(root, name)
	err := os.Remove(confPath)
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

func init() {
}
