package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/groot/homelab/internal/network"
	"github.com/groot/homelab/internal/network/tor"
	"github.com/groot/homelab/internal/tui/styles"
	"github.com/spf13/cobra"
)

const torContainer = "tor"

var torCmd = &cobra.Command{
	Use:   torContainer,
	Short: "Manage Tor onion service proxy",
	Long:  "Inspect gnzsnz/torproxy and manage .onion hidden services.",
}

// ── status ────────────────────────────────────────────────────────────────────

var torStatusCmd = &cobra.Command{
	Use:     "status",
	Aliases: []string{"ps"},
	Short:   "Show Tor container and onion service status",
	RunE: func(cmd *cobra.Command, args []string) error {
		root := configDir()
		if !extStatusHeader(root, "tor", torContainer, "Tor Onion Service Proxy") {
			return nil
		}

		// List active onion services
		torrcDir := filepath.Join(root, "tor", "torrc.d")
		entries, err := os.ReadDir(torrcDir)
		if err != nil {
			fmt.Printf("  %s  Could not read %s\n", styles.Warning.Render("!"), torrcDir)
			return nil
		}

		fmt.Printf("\n  %s\n", styles.Bold.Render("Active onion services"))
		found := false
		for _, e := range entries {
			if !strings.HasSuffix(e.Name(), ".conf") {
				continue
			}
			name := strings.TrimSuffix(e.Name(), ".conf")
			onion := torOnionAddress(name)
			if onion == "" {
				continue
			}
			found = true
			fmt.Printf("  %s  %s → %s",
				styles.Muted.Render("↳"),
				styles.Bold.Render(name),
				styles.Primary.Render(onion),
			)
			fmt.Println()
		}
		if !found {
			fmt.Printf("  %s  (none — run %s)\n",
				styles.Muted.Render("!"),
				styles.Primary.Render("homelab tor enable <service>"))
		}
		fmt.Println()
		return nil
	},
}

// ── logs ──────────────────────────────────────────────────────────────────────

var torLogsCmd = containerLogsCmd(torContainer,
	"Stream tor container logs")

// ── list ──────────────────────────────────────────────────────────────────────

var torListCmd = &cobra.Command{
	Use:   "list",
	Short: "List active onion services with .onion addresses",
	RunE: func(cmd *cobra.Command, args []string) error {
		root := configDir()
		torrcDir := filepath.Join(root, "tor", "torrc.d")
		entries, err := os.ReadDir(torrcDir)
		if err != nil {
			return fmt.Errorf("reading %s: %w", torrcDir, err)
		}

		fmt.Printf("\n%s\n\n", styles.Header.Render("Onion Services"))

		found := false
		for _, e := range entries {
			if !strings.HasSuffix(e.Name(), ".conf") {
				continue
			}
			name := strings.TrimSuffix(e.Name(), ".conf")
			onion := torOnionAddress(name)
			if onion == "" {
				fmt.Printf("  %s  %s  %s\n",
					styles.Warning.Render("!"), styles.Bold.Render(name),
					styles.Muted.Render("(container not running or service not yet ready)"))
				continue
			}
			found = true
			fmt.Printf("  %s  %s → %s\n",
				styles.Dot(true, true),
				styles.Bold.Render(name),
				styles.Primary.Render(onion),
			)
		}
		if !found {
			fmt.Printf("  %s  (none)\n", styles.Muted.Render("!"))
		}
		fmt.Println()
		return nil
	},
}

// ── enable ────────────────────────────────────────────────────────────────────

var torEnableCmd = &cobra.Command{
	Use:   "enable <service>",
	Short: "Expose a service as a .onion hidden service",
	Long: `Create a Tor hidden service for the given service.

The .onion address is auto-generated by Tor and persisted in the tor-data
Docker volume. If the volume is removed, the address changes.

After enabling, the .onion address can be found with:
  homelab tor list

Use --port to override the port detected from caddy.conf.`,
	Args:              cobra.ExactArgs(1),
	ValidArgsFunction: completeServiceNames,
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]
		root := configDir()

		port, _ := cmd.Flags().GetString("port")
		if port == "" {
			var err error
			port, err = detectServicePort(root, name)
			if err != nil {
				return fmt.Errorf("detecting port for %s: %w\n  Use --port to specify explicitly", name, err)
			}
		}

		portNum, err := strconv.Atoi(port)
		if err != nil {
			return fmt.Errorf("invalid port %q: %w", port, err)
		}

		l, err := torLayer()
		if err != nil {
			return err
		}
		// Same call path as `homelab enable <svc> --tor`: this command used to
		// keep its own copy of the torrc.d writer and the reload, which is how
		// the two came to disagree about whether a missing config is an error.
		if err := l.Enable(name, name, network.ServiceInfo{},
			[]network.PortSelection{{Name: "default", Port: portNum, Protocol: "tcp"}}); err != nil {
			return err
		}
		fmt.Printf("  %s  Hidden service configured and tor reloaded\n", styles.Success.Render("✓"))

		// Show .onion address if available
		if onion := torOnionAddress(name); onion != "" {
			fmt.Printf("  %s  Onion address: %s\n",
				styles.Primary.Render("→"),
				styles.Bold.Render(onion))
		} else {
			fmt.Printf("  %s  Onion address will appear after first connection — run %s\n",
				styles.Muted.Render("!"),
				styles.Primary.Render("homelab tor list"))
		}
		fmt.Println()

		return nil
	},
}

var torEnablePort string

func init() {
	torEnableCmd.Flags().StringVar(&torEnablePort, "port", "", "Override service port")
}

// ── disable ───────────────────────────────────────────────────────────────────

var torDisableCmd = &cobra.Command{
	Use:               "disable <service>",
	Short:             "Remove a .onion hidden service",
	Args:              cobra.ExactArgs(1),
	ValidArgsFunction: completeServiceNames,
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]

		l, err := torLayer()
		if err != nil {
			return err
		}
		if err := l.Disable(name); err != nil {
			return err
		}
		fmt.Printf("  %s  %s removed and tor reloaded\n\n",
			styles.Warning.Render("→"), styles.Bold.Render(name))
		return nil
	},
}

// ── helpers ───────────────────────────────────────────────────────────────────

// torLayer returns the registered Tor layer.
func torLayer() (*tor.Layer, error) {
	layer, ok := extRegistry().Get("tor")
	if !ok {
		return nil, fmt.Errorf("tor extension not registered")
	}
	l, ok := layer.(*tor.Layer)
	if !ok {
		return nil, fmt.Errorf("unexpected tor layer type %T", layer)
	}
	return l, nil
}

func init() {
	torCmd.AddCommand(torStatusCmd)
	torCmd.AddCommand(torLogsCmd)
	torCmd.AddCommand(torListCmd)
	torCmd.AddCommand(torEnableCmd)
	torCmd.AddCommand(torDisableCmd)
}
