package service_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/groot/homelab/internal/service"
)

// ── repo fixture helpers ──────────────────────────────────────────────────────

// newRepo creates a minimal homelab repo skeleton in a temp dir.
func newRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	for _, d := range []string{
		"caddy/conf.d",
		"caddy/conf.d-cf",
		"caddy/conf.d-tor",
		"caddy/conf.d-i2p",
		"caddy/conf.d-ygg",
		"caddy/conf.d-ipfs",
		"services",
	} {
		require.NoError(t, os.MkdirAll(filepath.Join(dir, d), 0o755))
	}
	return dir
}

// addService creates a minimal service directory. Optional files can be added
// by passing pairs of (relPath, content) via extras.
func addService(t *testing.T, repo, name string, extras ...string) string {
	t.Helper()
	svcDir := filepath.Join(repo, "services", name)
	require.NoError(t, os.MkdirAll(svcDir, 0o755))
	// Always write docker-compose.yml so validateService passes.
	write(t, filepath.Join(svcDir, "docker-compose.yml"), "services: {}\n")
	for i := 0; i+1 < len(extras); i += 2 {
		write(t, filepath.Join(svcDir, extras[i]), extras[i+1])
	}
	return svcDir
}

func write(t *testing.T, path, content string) {
	t.Helper()
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}

// enablePrivate writes a generated config file into caddy/conf.d/<name>.conf.
// Matches real behavior where configgen.WriteFile writes regular files.
func enablePrivate(t *testing.T, repo, name string) {
	t.Helper()
	dest := filepath.Join(repo, "caddy", "conf.d", name+".conf")
	write(t, dest, "# caddy private config (generated by configgen)\n")
}

// enablePublic writes a generated config file into caddy/conf.d-cf/<name>.conf.
// Matches real behavior where configgen.WriteFile writes regular files.
func enablePublic(t *testing.T, repo, name string) {
	t.Helper()
	dest := filepath.Join(repo, "caddy", "conf.d-cf", name+".conf")
	write(t, dest, "# caddy cf config (generated by configgen)\n")
}

// enableTor writes a generated config file into caddy/conf.d-tor/<name>.conf.
// Extension layers write regular files (not symlinks) via configgen.WriteFile.
func enableTor(t *testing.T, repo, name string) {
	t.Helper()
	dir := filepath.Join(repo, "caddy", "conf.d-tor")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	write(t, filepath.Join(dir, name+".conf"), "# tor config\n")
}

// enableI2P writes a generated config file into caddy/conf.d-i2p/<name>.conf.
func enableI2P(t *testing.T, repo, name string) {
	t.Helper()
	dir := filepath.Join(repo, "caddy", "conf.d-i2p")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	write(t, filepath.Join(dir, name+".conf"), "# i2p config\n")
}

// enableYgg writes a generated config file into caddy/conf.d-ygg/<name>.conf.
func enableYgg(t *testing.T, repo, name string) {
	t.Helper()
	dir := filepath.Join(repo, "caddy", "conf.d-ygg")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	write(t, filepath.Join(dir, name+".conf"), "# ygg config\n")
}

// enableIPFS writes a generated config file into caddy/conf.d-ipfs/<name>.conf.
func enableIPFS(t *testing.T, repo, name string) {
	t.Helper()
	dir := filepath.Join(repo, "caddy", "conf.d-ipfs")
	require.NoError(t, os.MkdirAll(dir, 0o755))
	write(t, filepath.Join(dir, name+".conf"), "# ipfs config\n")
}

// ── Discover ──────────────────────────────────────────────────────────────────

func TestDiscover_EmptyServicesDir(t *testing.T) {
	repo := newRepo(t)
	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	assert.Empty(t, svcs)
}

func TestDiscover_MissingServicesDir(t *testing.T) {
	dir := t.TempDir() // no services/ subdirectory
	svcs, err := service.Discover(dir)
	require.NoError(t, err)
	assert.Nil(t, svcs)
}

func TestDiscover_BasicService(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)

	svc := svcs[0]
	assert.Equal(t, "myapp", svc.Name)
	assert.Equal(t, filepath.Join(repo, "services", "myapp"), svc.Dir)
	assert.False(t, svc.HasCaddyConf)
	assert.False(t, svc.HasPublicCaddyConf)
	assert.False(t, svc.Enabled)
	assert.False(t, svc.PublicEnabled)
}

func TestDiscover_HasCaddyConf(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp", "caddy.conf", "# conf\n")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.True(t, svcs[0].HasCaddyConf)
	assert.False(t, svcs[0].HasPublicCaddyConf)
}

func TestDiscover_HasPublicCaddyConf(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp", "caddy.cf.conf", "# pub conf\n")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.False(t, svcs[0].HasCaddyConf)
	assert.True(t, svcs[0].HasPublicCaddyConf)
}

func TestDiscover_PrivateEnabled(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")
	enablePrivate(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.True(t, svcs[0].Enabled, "regular file in conf.d → Enabled=true")
	assert.False(t, svcs[0].PublicEnabled)
}

func TestDiscover_PublicEnabled(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")
	enablePublic(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.False(t, svcs[0].Enabled)
	assert.True(t, svcs[0].PublicEnabled, "regular file in conf.d-cf → PublicEnabled=true")
}

func TestDiscover_BothEnabled(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")
	enablePrivate(t, repo, "myapp")
	enablePublic(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.True(t, svcs[0].Enabled)
	assert.True(t, svcs[0].PublicEnabled)
}

func TestDiscover_MultipleServices_SortedAlphabetically(t *testing.T) {
	repo := newRepo(t)
	for _, name := range []string{"zebra", "alpha", "middle"} {
		addService(t, repo, name)
	}

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 3)

	names := []string{svcs[0].Name, svcs[1].Name, svcs[2].Name}
	assert.Equal(t, []string{"alpha", "middle", "zebra"}, names,
		"Discover must return services sorted alphabetically")
}

func TestDiscover_SkipsNonDirectories(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "realservice")
	// Write a plain file in services/ — should be ignored
	write(t, filepath.Join(repo, "services", "not-a-dir.txt"), "oops\n")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.Equal(t, "realservice", svcs[0].Name)
}

func TestDiscover_BrokenSymlinkNotCountedAsEnabled(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")

	// Create a broken symlink (target doesn't exist). With fileExists, os.Stat
	// follows the symlink and fails → Enabled=false.
	dest := filepath.Join(repo, "caddy", "conf.d", "myapp.conf")
	require.NoError(t, os.Symlink("/nonexistent/path/caddy.conf", dest))

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.False(t, svcs[0].Enabled,
		"broken symlink target not resolvable → Enabled=false")
}

// ── Network extension layer detection ─────────────────────────────────────────

func TestDiscover_TorLayer(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")
	enableTor(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.True(t, svcs[0].HasTor, "generated file in conf.d-tor → HasTor=true")
	assert.False(t, svcs[0].HasI2P)
	assert.False(t, svcs[0].HasYgg)
	assert.False(t, svcs[0].HasIPFS)
}

func TestDiscover_I2PLayer(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")
	enableI2P(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.True(t, svcs[0].HasI2P, "generated file in conf.d-i2p → HasI2P=true")
	assert.False(t, svcs[0].HasTor)
	assert.False(t, svcs[0].HasYgg)
	assert.False(t, svcs[0].HasIPFS)
}

func TestDiscover_YggLayer(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")
	enableYgg(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.True(t, svcs[0].HasYgg, "generated file in conf.d-ygg → HasYgg=true")
	assert.False(t, svcs[0].HasTor)
	assert.False(t, svcs[0].HasI2P)
	assert.False(t, svcs[0].HasIPFS)
}

func TestDiscover_IPFSLayer(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")
	enableIPFS(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.True(t, svcs[0].HasIPFS, "generated file in conf.d-ipfs → HasIPFS=true")
	assert.False(t, svcs[0].HasTor)
	assert.False(t, svcs[0].HasI2P)
	assert.False(t, svcs[0].HasYgg)
}

func TestDiscover_AllExtensionLayers(t *testing.T) {
	repo := newRepo(t)
	addService(t, repo, "myapp")
	enableTor(t, repo, "myapp")
	enableI2P(t, repo, "myapp")
	enableYgg(t, repo, "myapp")
	enableIPFS(t, repo, "myapp")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	require.Len(t, svcs, 1)
	assert.True(t, svcs[0].HasTor)
	assert.True(t, svcs[0].HasI2P)
	assert.True(t, svcs[0].HasYgg)
	assert.True(t, svcs[0].HasIPFS)
}

func TestDiscover_ExtensionLayerWithoutService(t *testing.T) {
	repo := newRepo(t)
	// Write a config file in conf.d-tor/ for a service that doesn't exist
	enableTor(t, repo, "nonexistent")

	svcs, err := service.Discover(repo)
	require.NoError(t, err)
	// The non-existent service should not appear in the list at all
	assert.Empty(t, svcs, "no service dir → no discovery, even with orphaned config")
}
