minero.{$PUB_SUBDOMAIN}.{$DOMAIN}:18080 {
    import wildcard_tls

    reverse_proxy monerod:18080
}

minero.{$PUB_SUBDOMAIN}.{$DOMAIN}:18084 {
    import wildcard_tls

    reverse_proxy monerod:18084
}

minero.{$PUB_SUBDOMAIN}.{$DOMAIN}:18089 {
    import wildcard_tls

    reverse_proxy monerod:18089
}

minero.{$PUB_SUBDOMAIN}.{$DOMAIN}:3333 {
    import wildcard_tls

    reverse_proxy p2pool:3333
}
