http://minero.{$DOMAIN}:18080 {


    reverse_proxy monerod:18080
}

http://minero.{$DOMAIN}:18084 {


    reverse_proxy monerod:18084
}

http://minero.{$DOMAIN}:18089 {


    reverse_proxy monerod:18089
}

http://minero.{$DOMAIN}:3333 {


    reverse_proxy p2pool:3333
}
