vars:
  WALLET_ADDRESS:
    value: "49NmBGozXvREQQokPw32DX7QK95xMFWPEbeLMZQmYUMf9r95kBv2cTeS45DNrLxq8fUPv7ct9rXjxNe4k4Ay65hHEJxoXdG"
    required: true
  MONEROD_HOST:
    value: "monerod"
    required: false
  P2POOL_HOST:
    value: "p2pool"
    required: false
ports:
  - 18080