services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    restart: unless-stopped
    environment:
      IPFS_PROFILE: ${IPFS_PROFILE:-server}
    volumes:
      - ipfs-data:/data/ipfs
      - ipfs-staging:/export
    networks:
      - home-services

networks:
  home-services:
    name: home-services
    external: true

volumes:
  ipfs-data:
    name: ipfs-data
  ipfs-staging:
    name: ipfs-staging
