http://immich.{$DOMAIN} {


    reverse_proxy immich:2283

    @uploads {
        method POST PUT PATCH
        path /api/asset* /api/upload*
    }
    route @uploads {
        request_body {
            max_size 10GB
        }
        reverse_proxy immich:2283 {
            transport http {
                read_timeout  0
                write_timeout 0
            }
        }
    }
}
