vars:
  DB_USERNAME:
    value: "immich"
    required: true
  DB_DATABASE_NAME:
    value: "immich"
    required: false
  IMMICH_VERSION:
    value: "release"
    required: false

secrets:
  DB_PASSWORD:
    required: true

databases:
  - postgres:
      host: immich-postgres
      port: 5432
      database: immich
      user: immich
      env:
        host: DB_HOSTNAME
        port: DB_PORT
  - redis:
      env:
        host: REDIS_HOSTNAME
        port: REDIS_PORT

ports:
  - 2283