# DOH
http://adguardhome.{$DOMAIN}:80 {


    reverse_proxy adguardhome:80
}
http://adguardhome.{$DOMAIN}:443 {


    reverse_proxy adguardhome:443
}
# DNS
http://adguardhome.{$DOMAIN}:53 {


    reverse_proxy adguardhome:53
}
# DOT
http://adguardhome.{$DOMAIN}:853 {


    reverse_proxy adguardhome:853
}
# DOQ
http://adguardhome.{$DOMAIN}:784 {


    reverse_proxy adguardhome:784
}
http://adguardhome.{$DOMAIN}:8853 {


    reverse_proxy adguardhome:8853
}
# DNSCrypt
http://adguardhome.{$DOMAIN}:5443 {


    reverse_proxy adguardhome:5443
}

