# DOH
adguardhome.{$PUB_SUBDOMAIN}.{$DOMAIN}:80 {
    import wildcard_tls

    reverse_proxy adguardhome:80
}
adguardhome.{$PUB_SUBDOMAIN}.{$DOMAIN}:443 {
    import wildcard_tls

    reverse_proxy adguardhome:443
}
# DNS
adguardhome.{$PUB_SUBDOMAIN}.{$DOMAIN}:53 {
    import wildcard_tls

    reverse_proxy adguardhome:53
}
# DOT
adguardhome.{$PUB_SUBDOMAIN}.{$DOMAIN}:853 {
    import wildcard_tls

    reverse_proxy adguardhome:853
}
# DOQ
adguardhome.{$PUB_SUBDOMAIN}.{$DOMAIN}:784 {
    import wildcard_tls

    reverse_proxy adguardhome:784
}
adguardhome.{$PUB_SUBDOMAIN}.{$DOMAIN}:8853 {
    import wildcard_tls

    reverse_proxy adguardhome:8853
}
# DNSCrypt
adguardhome.{$PUB_SUBDOMAIN}.{$DOMAIN}:5443 {
    import wildcard_tls

    reverse_proxy adguardhome:5443
}
# Admin panel
adguardhome.{$HOME_SUBDOMAIN}.{$DOMAIN} {
    import wildcard_tls

    reverse_proxy adguardhome:3000
}
