vars:
  TZ:
    value: "UTC"
    required: false

secrets: {}

databases:
  postgres:
    database: mattermost
    user: mattermost
    env:
      "postgres://{user}:{password}@{host}:{port}/{database}?sslmode=disable&connect_timeout=10": MM_DATASOURCE
