vars:
  TZ:
    value: "UTC"
    required: false

secrets: {}

databases:
  - postgres:
      database: mattermost
      user: mattermost
      dsn_template: "postgres://{user}:{password}@{host}:{port}/{database}?sslmode=disable&connect_timeout=10"
      env:
        dsn: MM_DATASOURCE
ports:
  web:
    port: 8065
