## i2pd configuration for homelab
## https://i2pd.readthedocs.io/en/latest/user-guide/configuration/

log = file
loglevel = info

ipv4 = true
ipv6 = false

[ntcp2]
enabled = true
published = true
port = 45678

[ssu2]
enabled = true
published = true
port = 45678

[http]
enabled = true
address = 0.0.0.0
port = 7070

[httpproxy]
enabled = true
address = 0.0.0.0
port = 4444

[socksproxy]
enabled = true
address = 0.0.0.0
port = 4447

[sam]
enabled = true
address = 0.0.0.0
port = 7656

[upnp]
enabled = false

[reseed]
verify = true

[addressbook]
enabled = true
defaulturl = http://reseed.i2p.net/hosts.txt
