http://nextcloud.{$DOMAIN} {


    reverse_proxy nextcloud:80

    header_up X-Real-IP {remote_host}
    header_up X-Forwarded-For {remote_host}
    header_up X-Forwarded-Proto {scheme}

    redir /.well-known/carddav /remote.php/dav 301
    redir /.well-known/caldav  /remote.php/dav 301
}
