package routing_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/groot/homelab/internal/configgen"
	"github.com/groot/homelab/internal/configgen/goldentest"
	"github.com/groot/homelab/internal/exposure"
	"github.com/groot/homelab/internal/network/layers"
	"github.com/groot/homelab/internal/routing"
)

// A service's sites file is exactly the golden per-layer blocks — the ones the
// layer packages pin — concatenated in registry order, each layer's blocks in
// port order. Ports resolve in key order (config.PortEntries is a map, so
// declaration order is not kept), which is also the order mesh ports were
// allocated in.
func TestGolden_SitesFileIsTheLayerBlocksInOrder(t *testing.T) {
	for _, svc := range goldentest.Services {
		t.Run(svc, func(t *testing.T) {
			root := t.TempDir()
			goldentest.Install(t, root, svc)
			reg := layers.New(root, nil, nil)

			// The daemon halves, as Configure would leave them: an onion in
			// tor's hostname file, and mesh ports in exposure.yaml.
			hs := filepath.Join(root, "tor", "hidden_service", svc)
			require.NoError(t, os.MkdirAll(hs, 0o700))
			require.NoError(t, os.WriteFile(filepath.Join(hs, "hostname"),
				[]byte(svc+"onionaddressxxxxxxxxxxxx.onion\n"), 0o600))
			e, err := configgen.Resolve(root, svc, "", nil)
			require.NoError(t, err)
			st := exposure.State{Layers: reg.Names(), YggPorts: map[string]int{}}
			for i, p := range e.Ports {
				st.YggPorts[exposure.MeshKey(p.Name)] = 9000 + i
			}
			require.NoError(t, exposure.Save(root, svc, st))

			require.NoError(t, routing.Sync(root, reg, svc))
			got := read(t, configgen.SitesFile(root, svc))
			require.True(t, strings.HasPrefix(got, "# Generated by homelab"), got)
			body := strings.SplitN(got, "\n", 3)[2]

			var want strings.Builder
			for _, l := range reg.All() {
				blocks := goldentest.Want(t, svc, l.LegacyConfDir())
				seen := map[string]bool{}
				for _, p := range e.Ports {
					name := configgen.PortFileName(svc, p.Name) + ".conf"
					if b, ok := blocks[name]; ok && !seen[name] {
						want.WriteString("\n" + b)
						seen[name] = true
					}
				}
				require.Len(t, seen, len(blocks), "%s: every golden block is placed", l.Name())
			}
			require.Equal(t, goldentest.Normalize(want.String()), goldentest.Normalize(body))
		})
	}
}
