// Package routing writes and removes a service's private (tailnet) Caddy route.
//
// Every route is generated by internal/configgen from the service's declared
// ports or its caddy.routes.conf. This package is the one place `homelab
// enable`, `disable` and `delete` go through, so they cannot drift on
// what "the private route" means. Neither function reloads Caddy: the callers
// batch every layer's writes and reload once.
package routing

import (
	"fmt"

	"github.com/groot/homelab/internal/configgen"
	"github.com/groot/homelab/internal/run"
)

// EnablePrivate writes the private tailnet route for a service.
//
// displayName overrides the subdomain (empty means the service name), and
// portNames restricts which declared ports get routed (empty means all). The
// Commander is unused since routes stopped being symlinks that reloaded Caddy
// themselves; it stays so callers need not change.
func EnablePrivate(root, svcName, displayName string, portNames []string, _ *run.Commander) error {
	info, err := configgen.LoadServiceInfo(root, svcName)
	if err != nil {
		return err
	}
	if info.Routes == "" && len(info.Ports) == 0 {
		return fmt.Errorf("no ports defined in config.yaml and no %s found for %s",
			configgen.RoutesFileName, svcName)
	}

	blocks, err := configgen.Generate(configgen.Request{
		ServiceName: svcName,
		DisplayName: displayName,
		Extensions:  []string{"private"},
		PortNames:   portNames,
		ConfigDir:   root,
	})
	if err != nil {
		return err
	}
	for _, b := range blocks {
		if b.Content == "" {
			continue // a raw TCP or UDP port: compose publishes it, Caddy cannot serve it
		}
		if err := configgen.WriteFile(root, b.Extension, svcName, b.PortName, b.Content); err != nil {
			return fmt.Errorf("writing private config: %w", err)
		}
	}
	return nil
}

// DisablePrivate removes the private route. An already-absent route is not an
// error: `delete` calls this only to make sure nothing is left behind.
func DisablePrivate(root, svcName string, _ *run.Commander) error {
	return configgen.RemoveAllPortFiles(root, "private", svcName)
}
